App\Infrastructure\Comment\Query\Projections\CommentView:
  type: entity
  table: comment
  indexes:
    fk_comment_user_idx:
      columns:
        - user
    fk_comment_post_idx:
      columns:
        - post
    fk_comment_comment_idx:
      columns:
        - parrent_comment
  id:
    id:
      type: string
      nullable: false
      length: 255
      options:
        fixed: false
      id: true
  fields:
    content:
      type: text
      nullable: false
      length: 65535
      options:
        fixed: false
    createdAt:
      type: datetime
      nullable: false
  manyToOne:
    parrentComment:
      targetEntity: CommentView
      cascade: [ remove ]
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        parrent_comment:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: true
    post:
      targetEntity: App\Infrastructure\Post\Query\Projections\PostView
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        post:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: false
    user:
      targetEntity: App\Infrastructure\User\Query\Projections\UserView
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        user:
          referencedColumnName: id
          onDelete: CASCADE
      orphanRemoval: false
  lifecycleCallbacks: {  }
