old_sound_rabbit_mq:
  connections:
    default:
      url: '%env(RABBITMQ_URL)%'
      lazy: true
      keepalive: false

  producers:
    events:
      connection:       default
      exchange_options: { name: 'events', type: topic }
#    projections:
#      class: App\Infrastructure\Share\Event\Producer\EventToProjectionsProducer
#      connection:       default
#      exchange_options: { name: 'events', type: topic }


  multiple_consumers:
    events:
      connection:       default
      exchange_options: { name: 'events', type: topic }
      queues:
        elastic_events:
          name: elastic_events
          routing_keys:
            - 'App.Domain.#'
          callback: App\Infrastructure\Share\Event\Consumer\SendEventsToElasticConsumer
#    projections:
#      connection:       default
#      exchange_options: { name: 'events', type: topic }
#      queues:
#        projections:
#          name: projections
#          routing_keys:
#            - 'projections'
#          callback: App\Infrastructure\Share\Event\Consumer\PublishProjectionsConsumer

