#index:
#    path: /
#    controller: App\Controller\DefaultController::index
# app/config/routing.yml
fos_oauth_server_token:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
  resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

add_category:
  path: /api/v1/category
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\CategoryController:createCategoryAction

edit_category:
  path: /api/v1/category/{id}
  methods: PATCH
  controller: App\UI\HTTP\Rest\Controller\CategoryController:changeNameAction

delete_category:
  path: /api/v1/category/{id}
  methods: DELETE
  controller: App\UI\HTTP\Rest\Controller\CategoryController:deleteCategoryAction

get_all_category:
  path: /api/category
  methods: GET
  controller: App\UI\HTTP\Rest\Controller\CategoryController:getAllCategoryAction

get_single_category:
  path: /api/category/{id}
  methods: GET
  controller: App\UI\HTTP\Rest\Controller\CategoryController:getSingleAction

add_user:
  path: /api/v1/user/register
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:createCategoryAction

confirm_user:
  path: /api/v1/user/confirm/{token}
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:confirmUserAction

banned_user:
  path: /api/v1/user/banned/{id}
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:bannedUserAction

change_user_name:
  path: /api/v1/user/change/username
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:changeNameAction

change_user_email:
  path: /api/v1/user/change/email
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:changeEmailAction

change_user_password:
  path: /api/v1/user/change/password
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:changePasswordAction

change_user_avatar:
  path: /api/v1/user/change/avatar
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\UserController:changeAvatar

get_all_user:
  path: /api/v1/user
  methods: GET
  controller: App\UI\HTTP\Rest\Controller\UserController:getAllAction

seciurity:
  path: /api/v1/seciurity
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\SecurityController:securityAction

add_post:
  path: /api/v1/post
  methods: POST
  controller: App\UI\HTTP\Rest\Controller\PostController:addPostAction

get_single_post:
  path: /api/v1/post/{id}
  methods: GET
  controller: App\UI\HTTP\Rest\Controller\PostController:getSingle

get_all_post:
  path: /api/v1/posts
  methods: GET
  controller: App\UI\HTTP\Rest\Controller\PostController:getAllAction

dashboard:
  path: /{react_link}
  methods: GET
  requirements:
    react_link: .+
  defaults:
    react_link: null
  controller: App\UI\HTTP\Rest\Controller\DashboardController:dashboard
