App\Infrastructure\Message\MessageView:
    type: entity
    table: message
    indexes:
        fk_message_user1_idx:
            columns:
                - sender
        fk_message_user2_idx:
            columns:
                - recipient
    id:
        id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true
    fields:
        content:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        displayed:
            type: boolean
            nullable: false
        createdAt:
            type: datetime
            nullable: false
    manyToOne:
        sender:
            targetEntity: App\Infrastructure\User\Query\Projections\UserView
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                sender:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
            nullable: false
        recipient:
            targetEntity: App\Infrastructure\User\Query\Projections\UserView
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                recipient:
                    referencedColumnName: id
                    onDelete: CASCADE
            orphanRemoval: false
            nullable: false
    lifecycleCallbacks: {  }
