App\Infrastructure\User\Query\Projections\UserView:
    type: entity
    table: fos_user
    id:
        id:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
            id: true

    fields:
        avatar:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        steemit:
            type: string
            nullable: true
            length: 255
            options:
                fixed: false
        banned:
            type: boolean
            nullable: false
            length: 1
            options:
                fixed: false
    oneToMany:
        comment:
            targetEntity: App\Infrastructure\Comment\Query\Projections\CommentView
            cascade: [ remove ]
            fetch: LAZY
            mappedBy: post
            inversedBy: null
            orphanRemoval: true
            nullable: true
        post:
            targetEntity: App\Infrastructure\Post\Query\Projections\PostView
            cascade: [ remove ]
            fetch: LAZY
            mappedBy: post
            inversedBy: null
            orphanRemoval: true
            nullable: true
        message:
            targetEntity: App\Infrastructure\Message\MessageView
            cascade: [ remove ]
            fetch: LAZY
            mappedBy: post
            inversedBy: null
            orphanRemoval: true
            nullable: true
        notification:
            targetEntity: App\Infrastructure\Notification\NotificationView
            cascade: [ remove ]
            fetch: LAZY
            mappedBy: post
            inversedBy: null
            orphanRemoval: true
            nullable: true

    lifecycleCallbacks: {  }
